safe:        true
auto:        false
server:      false
server_port: 80
base_url:    /
url:         http://crysol.github.io/

paginate:    8

lsi:         false
pygments:    true
markdown:    maruku
permalink:   date


redcarpet:
  extensions:
  render_options:
    - with_toc_data
    - hard_wrap
